from __future__ import annotations

from collections.abc import MutableMapping
from typing import Any

class NotebookNode(MutableMapping[str, Any]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

def from_dict(d: Any) -> Any: ...
