class _MemoryInfo:
    total: int
    free: int
    used: int

class _Utilization:
    gpu: int
    memory: int

class _Handle: ...

NVML_TEMPERATURE_GPU: int

def nvmlInit() -> None: ...
def nvmlShutdown() -> None: ...
def nvmlDeviceGetCount() -> int: ...
def nvmlDeviceGetHandleByIndex(index: int) -> _Handle: ...
def nvmlDeviceGetUtilizationRates(handle: _Handle) -> _Utilization: ...
def nvmlDeviceGetMemoryInfo(handle: _Handle) -> _MemoryInfo: ...
def nvmlDeviceGetTemperature(handle: _Handle, sensor: int) -> int: ...
