"""Independent schema versions for Runwatch's persisted and wire boundaries."""

CONFIG_SCHEMA_VERSION = 2
CLI_PRESENTATION_SCHEMA_VERSION = 1
DATABASE_SCHEMA_VERSION = 3
RUN_SNAPSHOT_SCHEMA_VERSION = 2
RUN_MANIFEST_SCHEMA_VERSION = 3
DASHBOARD_SCHEMA_VERSION = 1
NOTIFICATION_SCHEMA_VERSION = 1
RESOURCE_EVENT_SCHEMA_VERSION = 2
S3_PROGRESS_MANIFEST_SCHEMA_VERSION = 1
